[theme]
primaryColor = "#ff0000"
backgroundColor = "#000000"
secondaryBackgroundColor = "#111111"
textColor = "#FFFFFF"

[client]
showErrorDetails = true

[server]
headless = true

[browser]
gatherUsageStats = false
